title: "[Feature Request]: "
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: |
        Note: Search to make sure you aren't suggesting a duplicate feature.
        
        You can include screen-shots or gif examples of what you want to achieve.
  - type: dropdown
    id: plugin
    attributes:
      label: Server Plugin
      description: Which plugin is this for?
      options:
        - CrazyCrates
        - CrazyEnvoys
        - CrazyVouchers
        - CrazyEnchantments
        - ChatManager
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
